"""fix: relationship issues between job and job invoices

Revision ID: 452dcd76115c
Revises: cd57fa8f21bf
Create Date: 2023-05-20 09:48:51.203512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452dcd76115c'
down_revision = 'cd57fa8f21bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('job_invoices_job_id_fkey', type_='foreignkey')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('job_invoices_job_id_fkey', 'jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###
