"""update: client models

Revision ID: 4ac6fe8718a0
Revises: 452dcd76115c
Create Date: 2023-05-20 11:56:24.456272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac6fe8718a0'
down_revision = '452dcd76115c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_logo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('client_logo')

    # ### end Alembic commands ###
