"""fix: cycles between tables and missing migrations

Revision ID: 6557ef696721
Revises: cc198a814894
Create Date: 2023-05-19 20:01:01.825003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6557ef696721'
down_revision = 'cc198a814894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('jobs_job_invoice_id_fkey', type_='foreignkey')
        batch_op.drop_column('job_invoice_id')

    with op.batch_alter_table('jobs_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_invoice_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'job_invoices', ['job_invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs_statuses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_invoice_id')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_invoice_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('jobs_job_invoice_id_fkey', 'job_invoices', ['job_invoice_id'], ['id'])

    # ### end Alembic commands ###
