"""feat: updated existing model and created new ones (expenses, expenses type, income and income type)

Revision ID: cc198a814894
Revises: 458589b15985
Create Date: 2023-05-19 16:22:16.292401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc198a814894'
down_revision = '458589b15985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.String(), nullable=True))
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['registration_number'])
        batch_op.drop_constraint('clients_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('contact_persons', schema=None) as batch_op:
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('job_expenses', schema=None) as batch_op:
        batch_op.drop_constraint('job_expenses_job_invoice_id_fkey', type_='foreignkey')
        batch_op.drop_column('job_invoice_id')

    with op.batch_alter_table('job_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('job_invoices_client_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])
        batch_op.drop_column('client_id')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['contract_number'])
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])

    with op.batch_alter_table('jobs_statuses', schema=None) as batch_op:
        batch_op.drop_constraint('jobs_statuses_job_id_fkey', type_='foreignkey')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('services_job_id_fkey', type_='foreignkey')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('services_job_id_fkey', 'jobs', ['job_id'], ['id'])

    with op.batch_alter_table('jobs_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('jobs_statuses_job_id_fkey', 'jobs', ['job_id'], ['id'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('service_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('contract_number')

    with op.batch_alter_table('job_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_invoices_client_id_fkey', 'clients', ['client_id'], ['id'])
        batch_op.drop_column('job_id')

    with op.batch_alter_table('job_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_invoice_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('job_expenses_job_invoice_id_fkey', 'job_invoices', ['job_invoice_id'], ['id'])

    with op.batch_alter_table('contact_persons', schema=None) as batch_op:
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('clients_service_id_fkey', 'services', ['service_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###
