"""fix: relationship issues between job and job status

Revision ID: cd57fa8f21bf
Revises: e7c8aefd512d
Create Date: 2023-05-20 09:47:34.873545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd57fa8f21bf'
down_revision = 'e7c8aefd512d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobs_statuse_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'jobs_statuses', ['jobs_statuse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('jobs_statuse_id')

    # ### end Alembic commands ###
