"""client modal normalization

Revision ID: db9d9fb35372
Revises: 4ac6fe8718a0
Create Date: 2023-06-11 11:33:18.606465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9d9fb35372'
down_revision = '4ac6fe8718a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('street_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('zipcode', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(),
                            autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('street_name')

    # ### end Alembic commands ###
